#!/usr/bin/env bash
# Tests for lib/hooklib.sh
set -uo pipefail
# shellcheck source=../../../scripts/lib/testlib.sh
source "$(cd "$(dirname "$0")/../../../scripts/lib" && pwd)/testlib.sh"
t_init
LIB="$(dirname "$0")/../lib/hooklib.sh"
# shellcheck source=../lib/hooklib.sh
source "$LIB"

# planning_dir / ledger_path agree from a hook context and a bare git call (D4 parity)
expected="$(git rev-parse --show-toplevel)/.planning/LEDGER.tsv"
ok "ledger_path equals git-root/.planning/LEDGER.tsv" '[ "$(ledger_path)" = "$expected" ]'

# ledger_header is the canonical schema
ok "ledger_header schema" '[ "$(ledger_header)" = "$(printf "timestamp\tfiles\toutcome\tgate_result\tnotes")" ]'

# is_git_commit / is_git_push
ok "is_git_commit true"  'is_git_commit "git commit -m x"'
ok "is_git_push true"    'is_git_push "git push origin main"'
ok "is_git_commit false" '! is_git_commit "ls -la"'

# is_ai_attribution
ok "attr co-authored Claude" 'is_ai_attribution "Co-Authored-By: Claude <noreply@anthropic.com>"'
ok "attr generated by GPT"   'is_ai_attribution "Generated by GPT-4"'
ok "attr ignores plain name" '! is_ai_attribution "fix: issue reported by Claude (team member)"'
ok "attr co-authored Codex (F3/D1-5)"  'is_ai_attribution "Co-Authored-By: Codex <codex@openai.com>"'
ok "attr co-authored Devin"            'is_ai_attribution "Co-Authored-By: Devin <devin@cognition.ai>"'
ok "attr anthropic noreply any name"   'is_ai_attribution "Co-Authored-By: Fable <noreply@anthropic.com>"'
ok "attr still ignores human trailer"  '! is_ai_attribution "Co-Authored-By: Jane Doe <jane@example.com>"'

# is_ai_hint (attribution-shaped only; not bare vendor names)
ok "hint robot emoji"        'is_ai_hint "🤖 Generated with Claude Code"'
ok "hint AI-generated"       'is_ai_hint "This file is AI-generated"'
ok "hint ignores plain claude" '! is_ai_hint "claude config lives here"'

# is_gh_pr_text (PR-thread text surfaces; Finding X)
ok "gh pr comment is pr-text"   'is_gh_pr_text "gh pr comment 12 --body hi"'
ok "gh pr review is pr-text"    'is_gh_pr_text "gh pr review 12 --approve"'
ok "gh api comments is pr-text" 'is_gh_pr_text "gh api repos/o/r/issues/1/comments -f body=x"'
ok "gh pr list is not pr-text"  '! is_gh_pr_text "gh pr list"'
ok "plain git is not pr-text"   '! is_gh_pr_text "git status"'
# bracket-tolerant attribution (markdown-link footer)
ok "attr markdown-link footer" 'is_ai_attribution "Generated with [Claude Code](https://claude.com/claude-code)"'
ok "hint markdown-link footer" 'is_ai_hint "Generated with [Claude Code](https://claude.com/claude-code)"'

# repo_visibility resolves from the workspace-meta passport (this repo is private)
ok "repo_visibility private here" '[ "$(repo_visibility)" = "private" ]'

# is_ai_hint must NOT block a human co-author trailer (regression guard)
ok "hint ignores human co-author" '! is_ai_hint "Co-Authored-By: Jane Doe <jane@example.com>"'

# repo_visibility actually reads "public" from a passport (fixture proves the parse path)
fix=$(mktemp -d)
mkdir -p "$fix/myrepo" "$fix/workspace-meta/repos"
( cd "$fix/myrepo" && git init -q )
printf 'visibility: public\n' > "$fix/workspace-meta/repos/myrepo.md"
got_vis=$( cd "$fix/myrepo" && repo_visibility )
ok "repo_visibility public from fixture" '[ "$got_vis" = "public" ]'
# ai_mentions_allowed detects the marker
touch "$fix/myrepo/.ai-mentions-allowed"
ok "ai_mentions_allowed true with marker" '( cd "$fix/myrepo" && ai_mentions_allowed )'
rm -rf "$fix"

# write_state_atomic: exact content, overwrite, no temp residue, fail on missing dir
wsa=$(mktemp -d)
printf '{"phase":"x"}' > "$wsa/expected-x"
printf '{"phase":"x"}' | write_state_atomic "$wsa/state.json"
ok "write_state_atomic writes exact content" 'diff -q "$wsa/state.json" "$wsa/expected-x" >/dev/null'
printf '{"phase":"y"}' | write_state_atomic "$wsa/state.json"
printf '{"phase":"y"}' > "$wsa/expected-y"
ok "write_state_atomic overwrites in place" 'diff -q "$wsa/state.json" "$wsa/expected-y" >/dev/null'
ok "write_state_atomic leaves no temp residue" '[ -z "$(find "$wsa" -name ".wf-state.*" -print -quit)" ]'
ok "write_state_atomic fails on missing dir" '! ( printf "{}" | write_state_atomic "/no/such/dir/x.json" )'
rm -rf "$wsa"

# --- F4 / DUP-WSL-1: write_phase_state builds + atomically writes the canonical state object ---
wps=$(mktemp -d)
write_phase_state executing feat/x 2026-06-16T00:00:00Z "$wps/state.json"
ok "write_phase_state phase"      '[ "$(jq -r .phase "$wps/state.json")" = "executing" ]'
ok "write_phase_state branch"     '[ "$(jq -r .branch "$wps/state.json")" = "feat/x" ]'
ok "write_phase_state started_at" '[ "$(jq -r .started_at "$wps/state.json")" = "2026-06-16T00:00:00Z" ]'
ok "write_phase_state exactly 3 keys" '[ "$(jq -r "keys|length" "$wps/state.json")" = "3" ]'
ok "write_phase_state no temp residue" '[ -z "$(find "$wps" -name ".wf-state.*" -print -quit)" ]'
rm -rf "$wps"

# --- record_review_verdict: validation, schema, branch keying, default SHAs ---
rrv=$(mktemp -d)
( cd "$rrv" && git init -q && git checkout -q -b feature/rv \
  && git -c user.name=t -c user.email=t@t commit -q --allow-empty -m seed )
ok "rrv rejects bad verdict"   '! ( cd "$rrv" && record_review_verdict lgtm 2>/dev/null )'
ok "rrv rejects no verdict"    '! ( cd "$rrv" && record_review_verdict 2>/dev/null )'
ok "rrv writes approved"       '( cd "$rrv" && record_review_verdict approved abc123 def456 )'
ok "rrv branch recorded"       '[ "$(jq -r .branch "$rrv/.planning/review-state.json")" = "feature/rv" ]'
ok "rrv sha_range recorded"    '[ "$(jq -r .sha_range "$rrv/.planning/review-state.json")" = "abc123..def456" ]'
ok "rrv verdict recorded"      '[ "$(jq -r .verdict "$rrv/.planning/review-state.json")" = "approved" ]'
ok "rrv ts is ISO-8601 UTC"    'jq -r .ts "$rrv/.planning/review-state.json" | grep -qE "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]{8}Z$"'
ok "rrv default shas resolve"  '( cd "$rrv" && record_review_verdict changes-requested \
  && sha=$(git rev-parse HEAD) \
  && [ "$(jq -r .sha_range .planning/review-state.json)" = "${sha}..${sha}" ] )'
rm -rf "$rrv"

# hook_enabled: default on, disable-list, hard-pin, comma boundaries, no partial match
ok "hook_enabled default on" 'hook_enabled "pre-push-contract"'
ok "hook_enabled disabled via list" '! ( export WORKFLOW_DISABLED_HOOKS="pre-push-contract"; hook_enabled "pre-push-contract" )'
ok "hook_enabled pinned ignores disable" '( export WORKFLOW_DISABLED_HOOKS="secrets-scan"; hook_enabled "secrets-scan" )'
ok "hook_enabled list membership" '! ( export WORKFLOW_DISABLED_HOOKS="a,pre-push-contract,b"; hook_enabled "pre-push-contract" )'
ok "hook_enabled no partial match" '( export WORKFLOW_DISABLED_HOOKS="pre-push"; hook_enabled "pre-push-contract" )'

# emit_additional_context: valid envelope, correct event + message, jq-safe escaping
emitted="$(emit_additional_context PostToolUse 'hello world')"
ok "emit event name"  '[ "$(printf "%s" "$emitted" | jq -r .hookSpecificOutput.hookEventName)" = "PostToolUse" ]'
ok "emit message"     '[ "$(printf "%s" "$emitted" | jq -r .hookSpecificOutput.additionalContext)" = "hello world" ]'
ok "emit escapes quotes" '[ "$(emit_additional_context PreToolUse "a \"q\" b" | jq -r .hookSpecificOutput.additionalContext)" = "a \"q\" b" ]'

# --- safe_slug (I7): canonical id normalizer; wf_safe_id delegates byte-identically ---
ok "safe_slug a/b|c -> a_b_c"        '[ "$(safe_slug "a/b|c")" = "a_b_c" ]'
ok "safe_slug empty -> nosession"    '[ "$(safe_slug "")" = "nosession" ]'
ok "safe_slug empty honors fallback" '[ "$(safe_slug "" alt)" = "alt" ]'
ok "wf_safe_id delegates to safe_slug" '[ "$(wf_safe_id "a/b|c")" = "$(safe_slug "a/b|c")" ]'

# --- cfg_int: adversarial fixtures ---
# Every bad input returns the DEFAULT, exit 0, and writes NOTHING to stderr.
for bad in '' '-' '--' '5-5' '1-' '-7' '12-34-56' '9999999999999999999999' '0x1F' '+5' ' 5' '5 ' 'abc'; do
  out="$(CFGV="$bad" cfg_int CFGV 35 2 99 2>/tmp/cfgerr.$$)"
  ok "cfg_int rejects [$bad] -> default" '[ "$out" = "35" ]'
  ok "cfg_int [$bad] no stderr" '[ ! -s /tmp/cfgerr.$$ ]'
done
rm -f /tmp/cfgerr.$$
ok "cfg_int 007 -> 7 (canonicalized)" '[ "$(CFGV=007 cfg_int CFGV 35 2 99)" = "7" ]'
ok "cfg_int 35 -> 35"                  '[ "$(CFGV=35  cfg_int CFGV 35 2 99)" = "35" ]'
ok "cfg_int out-of-range high -> def"  '[ "$(CFGV=500 cfg_int CFGV 35 2 99)" = "35" ]'
ok "cfg_int out-of-range low -> def"   '[ "$(CFGV=1   cfg_int CFGV 35 2 99)" = "35" ]'
ok "cfg_int unset -> default"          '[ "$(unset CFGV; cfg_int CFGV 35 2 99)" = "35" ]'
# --- cfg_flag: case-insensitive truthy/falsy, garbage -> default ---
ok "cfg_flag on -> 1"      '[ "$(CFGF=on    cfg_flag CFGF 0)" = "1" ]'
ok "cfg_flag TRUE -> 1"    '[ "$(CFGF=TRUE  cfg_flag CFGF 0)" = "1" ]'
ok "cfg_flag No -> 0"      '[ "$(CFGF=No    cfg_flag CFGF 1)" = "0" ]'
ok "cfg_flag junk -> def1" '[ "$(CFGF=junk  cfg_flag CFGF 1)" = "1" ]'
ok "cfg_flag junk -> def0" '[ "$(CFGF=junk  cfg_flag CFGF 0)" = "0" ]'
ok "cfg_flag unset -> def" '[ "$(unset CFGF; cfg_flag CFGF 0)" = "0" ]'
CFGF=junk cfg_flag CFGF 0 >/dev/null 2>/tmp/cfgferr.$$
ok "cfg_flag junk no stderr" '[ ! -s /tmp/cfgferr.$$ ]'
rm -f /tmp/cfgferr.$$

# --- audit_log: one JSON line per call, valid JSON, append-not-lost, size-bounded ---
adir="$(mktemp -d)"; af="$adir/phase4.jsonl"
WORKFLOW_AUDIT_PATH="$af" audit_log '{"v":1,"hook":"t","result":"none"}'
WORKFLOW_AUDIT_PATH="$af" audit_log '{"v":1,"hook":"t","result":"soft"}'
ok "audit wrote 2 lines"          '[ "$(wc -l < "$af")" -eq 2 ]'
ok "audit line 1 valid JSON"      'jq -e . <(sed -n 1p "$af") >/dev/null'
ok "audit line 2 result=soft"     '[ "$(sed -n 2p "$af" | jq -r .result)" = "soft" ]'
for i in $(seq 1 30); do WORKFLOW_AUDIT_PATH="$af" audit_log "{\"v\":1,\"n\":$i}" & done; wait
ok "audit no lost appends (>=32 lines)" '[ "$(wc -l < "$af")" -ge 32 ]'
ok "audit all lines valid JSON"   'while IFS= read -r l; do jq -e . <<<"$l" >/dev/null || exit 1; done < "$af"'
big="{\"x\":\"$(head -c 4000 < /dev/zero | tr "\0" x)\"}"
before="$(wc -l < "$af")"
WORKFLOW_AUDIT_PATH="$af" audit_log "$big"
ok "audit drops >3500B line" '[ "$(wc -l < "$af")" -eq "$before" ]'
off_before="$(wc -l < "$af")"
WORKFLOW_AUDIT=off WORKFLOW_AUDIT_PATH="$af" audit_log '{"v":1}'
ok "audit off -> no write" '[ "$(wc -l < "$af")" -eq "$off_before" ]'
rm -rf "$adir"
# --- wf_reaper: deletes stale, keeps fresh, fail-open on missing dir ---
rdir="$(mktemp -d)"; touch "$rdir/old.warned" "$rdir/new.warned"
touch -d '30 days ago' "$rdir/old.warned" 2>/dev/null || touch -t 202601010000 "$rdir/old.warned"
WORKFLOW_TMP_TTL_DAYS=7 wf_reaper "$rdir" '*.warned'
ok "reaper deleted stale"  '[ ! -e "$rdir/old.warned" ]'
ok "reaper kept fresh"     '[ -e "$rdir/new.warned" ]'
ok "reaper missing dir ok" 'wf_reaper "/no/such/dir" "*.warned"; [ $? -eq 0 ]'
rm -rf "$rdir"

# ledger_validate / ledger_stats (P3 — one enforced ledger, Finding M)
ltmp=$(mktemp -d)
printf 'timestamp\tfiles\toutcome\tgate_result\tnotes\n2026-06-04\tx\tkept\tok\tn\n2026-06-04\ty\tdiscarded\tno win\tn\n' > "$ltmp/good.tsv"
printf 'timestamp\tfiles\toutcome\tgate_result\tnotes\n2026-06-04\tx\tkeep\tok\tn\n' > "$ltmp/badout.tsv"
printf 'timestamp\tfiles\toutcome\tgate_result\tnotes\n2026-06-04\tx\tkept\tok\n' > "$ltmp/badcols.tsv"
printf 'wrong\theader\n2026-06-04\tx\tkept\tok\tn\n' > "$ltmp/badhdr.tsv"
printf 'timestamp\tfiles\toutcome\tgate_result\tnotes\n2026-06-04\tx\tkept\tok\tn\n\n' > "$ltmp/blankpad.tsv"
ok "ledger_validate clean file rc0"   'ledger_validate "$ltmp/good.tsv"'
ok "ledger_validate missing file rc0" 'ledger_validate "$ltmp/absent.tsv"'
ok "ledger_validate bad outcome rc1"  '! ledger_validate "$ltmp/badout.tsv"'
# NOTE: capture-then-compare, NOT `ledger_validate | grep` — the file runs under
# `set -uo pipefail` and ledger_validate's deliberate rc 1 would poison the pipeline
# status even when grep matches. Command substitution discards the rc.
ok "ledger_validate names the vocab"  '[[ "$(ledger_validate "$ltmp/badout.tsv")" == *"not in kept|discarded|dead-end"* ]]'
ok "ledger_validate bad columns rc1"  '! ledger_validate "$ltmp/badcols.tsv"'
ok "ledger_validate bad header rc1"   '! ledger_validate "$ltmp/badhdr.tsv"'
ok "ledger_validate ignores blank padding" 'ledger_validate "$ltmp/blankpad.tsv"'
ok "ledger_stats counts outcomes"     '[ "$(ledger_stats "$ltmp/good.tsv")" = "kept=1 discarded=1 dead-end=0" ]'
ok "ledger_stats missing file zeros"  '[ "$(ledger_stats "$ltmp/absent.tsv")" = "kept=0 discarded=0 dead-end=0" ]'
ok "repo LEDGER passes validator"     'ledger_validate'
rm -rf "$ltmp"

# --- F4 / DUP-2: ledger_rows counts schema-shaped data rows (NF==5, non-header) ---
lr=$(mktemp -d)
printf 'timestamp\tfiles\toutcome\tgate_result\tnotes\n2026-06-04\tx\tkept\tok\tn\n2026-06-04\ty\tdiscarded\tno win\tn\n\n2026-06-04\tz\tkept\tok\n' > "$lr/mixed.tsv"
# rows: 2 valid (NF==5) + 1 blank (NF==0, skip) + 1 malformed (NF==4, skip) = 2
ok "ledger_rows counts only NF==5 data rows" '[ "$(ledger_rows "$lr/mixed.tsv")" = "2" ]'
ok "ledger_rows missing file -> 0" '[ "$(ledger_rows "$lr/absent.tsv")" = "0" ]'
ok "ledger_rows header-only -> 0" '{ printf "timestamp\tfiles\toutcome\tgate_result\tnotes\n" > "$lr/h.tsv"; [ "$(ledger_rows "$lr/h.tsv")" = "0" ]; }'
rm -rf "$lr"

# --- F4 / DUP-2: ledger_rows --since-ref is diff-scoped (SHA-anchored, not timestamp) ---
lrr=$(mktemp -d)
( cd "$lrr" && git init -q -b main && git config user.email t@t && git config user.name t
  printf 'timestamp\tfiles\toutcome\tgate_result\tnotes\n2026-05-01\ta\tkept\tok\told1\n2026-05-02\tb\tkept\tok\told2\n' > L.tsv
  git add L.tsv && git commit -q -m seed
  git update-ref refs/remotes/origin/main HEAD
  git checkout -q -b feat
  printf '2026-06-16T08:00:00Z\tc\tkept\tok\tnew1\n' >> L.tsv && git add L.tsv && git commit -q -m f1
  printf '2026-06-16T08:10:00Z\td\tkept\tok\tnew2\n' >> L.tsv && git add L.tsv && git commit -q -m f2 )
mb=$( cd "$lrr" && git merge-base HEAD origin/main )
ok "ledger_rows --since-ref counts only this branch's net-added rows" \
  '[ "$( cd "$lrr" && ledger_rows --since-ref "$mb" L.tsv )" = "2" ]'
ok "ledger_rows --since-ref cumulative-degrades on empty ref" \
  '[ "$( cd "$lrr" && ledger_rows --since-ref "" L.tsv )" = "4" ]'
ok "ledger_rows --since-ref cumulative-degrades when ref==HEAD" \
  '[ "$( cd "$lrr" && ledger_rows --since-ref HEAD L.tsv )" = "4" ]'
ok "ledger_rows --since-ref cumulative-degrades on unresolvable ref" \
  '[ "$( cd "$lrr" && ledger_rows --since-ref deadbeef L.tsv )" = "4" ]'
rm -rf "$lrr"

# --- F3: unpushed_range — one canonical push range (D1-2, DUP-7) ---
upr=$(mktemp -d)
git init -q --bare "$upr/origin.git"
git clone -q "$upr/origin.git" "$upr/wc" 2>/dev/null
(
  cd "$upr/wc" && git checkout -q -b main &&
  git -c user.email=t@t -c user.name=t commit -q --allow-empty -m base &&
  git push -q -u origin main 2>/dev/null &&
  git checkout -q -b feat
)
got_first=$( cd "$upr/wc" && unpushed_range )
ok "unpushed_range first push falls back to origin/main" '[ "$got_first" = "origin/main..HEAD" ]'
( cd "$upr/wc" && git push -q -u origin feat 2>/dev/null )
got_up=$( cd "$upr/wc" && unpushed_range )
ok "unpushed_range prefers the upstream/push branch" '[ "$got_up" = "origin/feat..HEAD" ]'
norepo=$(mktemp -d)
( cd "$norepo" && git init -q -b main && git -c user.email=t@t -c user.name=t commit -q --allow-empty -m x )
got_none=$( cd "$norepo" && unpushed_range )
ok "unpushed_range no origin at all -> empty" '[ -z "$got_none" ]'
ok "unpushed_range always rc 0" '( cd "$norepo" && unpushed_range >/dev/null )'
rm -rf "$upr" "$norepo"

# --- F3: wf_log_skip_debounced optional reason (engine-fallback audit) ---
dbt=$(mktemp -d)
TMPDIR="$dbt" WORKFLOW_AUDIT_PATH="$dbt/a.jsonl" wf_log_skip_debounced f3-test-id engine_fallback_builtin
ok "skip-debounce custom reason recorded" '[ "$(tail -n1 "$dbt/a.jsonl" | jq -r .reason)" = "engine_fallback_builtin" ]'
TMPDIR="$dbt" WORKFLOW_AUDIT_PATH="$dbt/a.jsonl" wf_log_skip_debounced f3-test-id engine_fallback_builtin
ok "skip-debounce still debounces with reason" '[ "$(wc -l < "$dbt/a.jsonl")" -eq 1 ]'
rm -rf "$dbt"

# --- F3 / D5-1: hybrid secret engine (gitleaks layer over the builtin floor) ---
AGE_TKN="AGE-SECRET-KEY-1$(printf 'Q%.0s' $(seq 1 58))"   # assembled; default ruleset class the floor misses
GHP_TKN="ghp_""ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij"
flr=$(printf 'T=%s\n' "$GHP_TKN" | WORKFLOW_SECRETS_GITLEAKS=off secret_matches_blocking)
ok "blocking tier keeps builtin floor with engine off" '[ -n "$flr" ]'
if command -v gitleaks >/dev/null 2>&1; then
  glo=$(printf 'k=%s\n' "$AGE_TKN" | secret_matches_gitleaks)
  ok "gitleaks engine finds age-key class" '[ -n "$glo" ]'
  ok "gitleaks engine respects off flag (rc1)" '! ( printf "x" | WORKFLOW_SECRETS_GITLEAKS=off secret_matches_gitleaks )'
  blk=$(printf 'k=%s\n' "$AGE_TKN" | secret_matches_blocking)
  ok "blocking tier includes gitleaks layer" '[ -n "$blk" ]'
  un=$(printf 'k=%s\n' "$AGE_TKN" | secret_matches)
  ok "secret_matches union includes gitleaks layer" '[ -n "$un" ]'
  cln=$(printf 'plain text only\n' | secret_matches_blocking)
  ok "blocking tier clean input stays clean" '[ -z "$cln" ]'

  # Error-path: a stub gitleaks that exits rc=1 with empty stdout (config/runtime error)
  # must cause secret_matches_blocking to write an engine_fallback_builtin audit line.
  # Use a fresh TMPDIR so the debounce marker for secret-engine-gitleaks is not already set.
  _err_dir=$(mktemp -d)
  cat > "$_err_dir/gitleaks" <<'STUB'
#!/bin/sh
exit 1
STUB
  chmod +x "$_err_dir/gitleaks"
  _err_audit="$_err_dir/audit.jsonl"
  # Run the blocking tier in a subshell so env overrides are isolated; check the
  # audit file in the outer shell after the subshell exits (the file is on-disk).
  ( export TMPDIR="$_err_dir"; export WORKFLOW_AUDIT_PATH="$_err_audit"
    export PATH="$_err_dir:$PATH"
    printf "plain\n" | secret_matches_blocking >/dev/null 2>&1 )
  ok "engine config/runtime error (rc=1) triggers fallback audit line" \
    '[ -s "$_err_audit" ] && grep -q "engine_fallback_builtin" "$_err_audit"'
  rm -rf "$_err_dir"
else
  echo "SKIP: gitleaks not on PATH — engine-layer cases skipped (floor case above still ran)"
fi

# --- F4 / D4-2: gate_cmd_kind classifies acceptance-gate commands (single source) ---
ok "gate_cmd_kind make hooks-test -> test"  '[ "$(gate_cmd_kind "make hooks-test")" = "test" ]'
ok "gate_cmd_kind pytest -> test"           '[ "$(gate_cmd_kind "pytest -q tests/")" = "test" ]'
ok "gate_cmd_kind bash test- -> test"       '[ "$(gate_cmd_kind "bash .claude/hooks/tests/test-x.sh")" = "test" ]'
ok "gate_cmd_kind shellcheck -> lint"       '[ "$(gate_cmd_kind "shellcheck -x foo.sh")" = "lint" ]'
ok "gate_cmd_kind golangci-lint -> lint"    '[ "$(gate_cmd_kind "golangci-lint run")" = "lint" ]'
ok "gate_cmd_kind gitleaks -> secrets"      '[ "$(gate_cmd_kind "gitleaks dir .")" = "secrets" ]'
ok "gate_cmd_kind plain git -> empty"       '[ -z "$(gate_cmd_kind "git status")" ]'
ok "gate_cmd_kind ls -> empty"              '[ -z "$(gate_cmd_kind "ls -la")" ]'
# false-positive guards (word-boundary + git-skip): tool names inside filenames/args/messages
ok "gate_cmd_kind git commit w/ pytest in msg -> empty" '[ -z "$(gate_cmd_kind "git commit -m \"add pytest config\"")" ]'
ok "gate_cmd_kind cat gitleaks-config file -> empty"    '[ -z "$(gate_cmd_kind "cat gitleaksconfig.toml")" ]'
ok "gate_cmd_kind rm pytest_cache -> empty"             '[ -z "$(gate_cmd_kind "rm pytest_cache")" ]'

# --- F4 / D4-2: resolve_gate_status defensive pass|fail|unknown over tool_response shapes ---
gs() { printf '%s' "$1" | resolve_gate_status | cut -f1; }    # status only
gx() { printf '%s' "$1" | resolve_gate_status | cut -f3; }    # src only
ok "status numeric exit 0 -> pass"   '[ "$(gs "{\"exit_code\":0}")" = "pass" ]'
ok "status numeric exit 1 -> fail"   '[ "$(gs "{\"exit_code\":1}")" = "fail" ]'
ok "status exitCode alias -> fail"   '[ "$(gs "{\"exitCode\":2}")" = "fail" ]'
ok "status success:true -> pass"     '[ "$(gs "{\"success\":true}")" = "pass" ]'
ok "status is_error:true -> fail"    '[ "$(gs "{\"is_error\":true}")" = "fail" ]'
ok "status interrupted -> fail"      '[ "$(gs "{\"interrupted\":true}")" = "fail" ]'
ok "status stdout marker -> pass"    '[ "$(gs "{\"stdout\":\"Results: 12 passed, 0 failed\"}")" = "pass" ]'
ok "status stderr marker -> fail"    '[ "$(gs "{\"stderr\":\"FAILED: boom\"}")" = "fail" ]'
ok "status indeterminate -> unknown" '[ "$(gs "{\"stdout\":\"hello world\"}")" = "unknown" ]'
ok "status empty object -> unknown"  '[ "$(gs "{}")" = "unknown" ]'
ok "status src records the rung"     '[ "$(gx "{\"exit_code\":0}")" = "exit_code" ]'
ok "status src for boolean rung"     '[ "$(gx "{\"success\":true}")" = "success" ]'
ok "status src for marker rung"      '[ "$(gx "{\"stdout\":\"all tests passed\"}")" = "stdout_marker" ]'
ok "status no-failure summary -> pass (0 failed regression)" '[ "$(gs "{\"stdout\":\"Results: 12 passed, 0 failed\"}")" = "pass" ]'
ok "status real failure summary -> fail" '[ "$(gs "{\"stdout\":\"Results: 3 passed, 2 failed\"}")" = "fail" ]'

# --- F4 / D4-2: gate_evidence_log appends one valid JSONL line; off-switch + path guard ---
gel=$(mktemp -d)
( cd "$gel" && git init -q && git config user.email t@t && git config user.name t && mkdir -p .planning )
( cd "$gel" && gate_evidence_log pass 0 test "make hooks-test" exit_code )
elog="$gel/.planning/gate-evidence.log"
ok "gate_evidence_log wrote one JSONL line" '[ "$( cd "$gel" && wc -l < "$elog" )" = "1" ]'
ok "gate_evidence_log line is valid JSON"   'jq -e . <(tail -n1 "$elog") >/dev/null'
ok "gate_evidence_log status field"         '[ "$(tail -n1 "$elog" | jq -r .status)" = "pass" ]'
ok "gate_evidence_log exit is numeric"      '[ "$(tail -n1 "$elog" | jq -r .exit)" = "0" ]'
ok "gate_evidence_log kind field"           '[ "$(tail -n1 "$elog" | jq -r .kind)" = "test" ]'
ok "gate_evidence_log off-switch suppresses" \
  '{ before=$( cd "$gel" && wc -l < "$elog" ); ( cd "$gel" && WORKFLOW_GATE_EVIDENCE=off gate_evidence_log pass 0 test x src ); [ "$( cd "$gel" && wc -l < "$elog" )" = "$before" ]; }'
ok "gate_evidence_log file is owner-only (0600)" '[ "$(stat -c %a "$elog")" = "600" ]'
rm -rf "$gel"

t_summary
