#!/usr/bin/env bash
# Tests for forbidden-ai-attribution.sh hook
set -euo pipefail
# shellcheck source=../../../scripts/lib/testlib.sh
source "$(cd "$(dirname "$0")/../../../scripts/lib" && pwd)/testlib.sh"
t_init
HOOK="$(cd "$(dirname "$0")/.." && pwd)/forbidden-ai-attribution.sh"

run_test() {
  local name="$1" input="$2" expect_exit="$3"
  actual_exit=0
  output=$(echo "$input" | bash "$HOOK" 2>&1) || actual_exit=$?
  if [ "$actual_exit" -eq "$expect_exit" ]; then
    echo "PASS: $name"
    pass=$((pass+1))
  else
    echo "FAIL: $name (expected exit $expect_exit, got $actual_exit)"
    echo "  output: $output"
    fail=$((fail+1))
  fi
}

# Should block: Co-Authored-By Claude
run_test "block co-authored-by Claude" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"feat: add feature\n\nCo-Authored-By: Claude <noreply@anthropic.com>\""}}' \
  2

# Should block: Generated by AI
run_test "block generated by AI" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"Generated by Claude Code\""}}' \
  2

# Should block: Built with GPT
run_test "block built with GPT" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"Built with GPT-4\""}}' \
  2

# Should block: Assisted by Copilot
run_test "block assisted by Copilot" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"Assisted by Copilot\""}}' \
  2

# Should block: Co-Authored-By Anthropic
run_test "block co-authored-by Anthropic" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"fix: stuff\n\nCo-Authored-By: Anthropic AI\""}}' \
  2

# Should block: HEREDOC with attribution
run_test "block HEREDOC attribution" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"$(cat <<'\''EOF'\''\nfeat: thing\n\nCo-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>\nEOF\n)\""}}' \
  2

# Should allow: normal commit
run_test "allow normal commit" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"feat: add user authentication\""}}' \
  0

# Should allow: non-git bash command
run_test "allow non-git bash" \
  '{"tool_name":"Bash","tool_input":{"command":"ls -la"}}' \
  0

# Should allow: non-Bash tool
run_test "passthrough non-Bash" \
  '{"tool_name":"Write","tool_input":{"file_path":"x.py","content":"hello"}}' \
  0

# Should allow: commit mentioning "Claude" as a person name (no attribution pattern)
run_test "allow Claude as name" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"fix: resolve issue reported by Claude (team member)\""}}' \
  0

# --- gh PR-thread surfaces (Finding X) ---
run_test "block gh pr comment with plugin footer" \
  '{"tool_name":"Bash","tool_input":{"command":"gh pr comment 12 --body \"Looks good\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\""}}' \
  2

run_test "block gh pr review with co-author trailer" \
  '{"tool_name":"Bash","tool_input":{"command":"gh pr review 12 --approve --body \"Co-Authored-By: Claude <noreply@anthropic.com>\""}}' \
  2

run_test "block gh api comments with attribution" \
  '{"tool_name":"Bash","tool_input":{"command":"gh api repos/o/r/issues/12/comments -f body=\"Generated by Claude\""}}' \
  2

bf=$(mktemp)
printf '🤖 Generated with [Claude Code](https://claude.com/claude-code)\n' > "$bf"
run_test "block gh pr comment --body-file with footer" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"gh pr comment 12 --body-file $bf\"}}" \
  2

# Quoted body-file path (mainstream shell idiom for paths with spaces) must still be scanned.
run_test "block gh pr comment --body-file with quoted path" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"gh pr comment 12 --body-file \\\"$bf\\\"\"}}" \
  2
rm -f "$bf"

# Quoted body-file path that ACTUALLY contains a space — the spaced-path capture
# must survive the interior space, not stop at the first one.
spacedir=$(mktemp -d)
spacebf="$spacedir/my notes.md"
printf 'Co-Authored-By: Claude <noreply@anthropic.com>\n' > "$spacebf"
run_test "block gh pr comment --body-file with spaced quoted path" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"gh pr comment 12 --body-file \\\"$spacebf\\\"\"}}" \
  2
# body=@"..." analog with a space in the path.
run_test "block gh api body=@ with spaced quoted path" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"gh api repos/o/r/issues/12/comments -f body=@\\\"$spacebf\\\"\"}}" \
  2
rm -rf "$spacedir"

run_test "allow clean gh pr comment" \
  '{"tool_name":"Bash","tool_input":{"command":"gh pr comment 12 --body \"LGTM - merging after CI\""}}' \
  0

run_test "allow gh pr list (not a text surface)" \
  '{"tool_name":"Bash","tool_input":{"command":"gh pr list --state merged"}}' \
  0

# bracket-tolerant attribution now also guards commits
run_test "block commit with [Claude Code] footer" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"feat: x\n\nGenerated with [Claude Code](https://claude.com/claude-code)\""}}' \
  2

# F2: a block must leave an audit line.
alog="$(mktemp -d)/audit.jsonl"
blocking_payload='{"tool_name":"Bash","tool_input":{"command":"git commit -m \"feat: add feature\n\nCo-Authored-By: Claude <noreply@anthropic.com>\""}}'
printf '%s' "$blocking_payload" | WORKFLOW_AUDIT_PATH="$alog" bash "$HOOK" >/dev/null 2>&1 || true
if [ -s "$alog" ] && tail -n1 "$alog" | jq -e '.result=="block"' >/dev/null 2>&1; then
  echo "PASS: block audited"
  pass=$((pass+1))
else
  echo "FAIL: no audit line on block"; fail=$((fail+1))
fi

# --- F3 / D1-2: first-push scan via origin fallback (sandbox repo) ---
sb=$(mktemp -d)
(
  cd "$sb" && git init -q -b main &&
  git -c user.email=t@t -c user.name=t commit -q --allow-empty -m base &&
  git update-ref refs/remotes/origin/main HEAD &&
  git checkout -q -b feat/first &&
  git -c user.email=t@t -c user.name=t commit -q --allow-empty \
    -m $'feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>'
)
rc=0
printf '%s' '{"tool_name":"Bash","tool_input":{"command":"git push -u origin feat/first"}}' \
  | ( cd "$sb" && bash "$HOOK" ) >/dev/null 2>&1 || rc=$?
if [ "$rc" -eq 2 ]; then echo "PASS: first-push attribution blocked (D1-2)"; pass=$((pass+1));
else echo "FAIL: first-push attribution NOT blocked (exit=$rc)"; fail=$((fail+1)); fi

# clean first push passes
sb2=$(mktemp -d)
(
  cd "$sb2" && git init -q -b main &&
  git -c user.email=t@t -c user.name=t commit -q --allow-empty -m base &&
  git update-ref refs/remotes/origin/main HEAD &&
  git checkout -q -b feat/clean &&
  git -c user.email=t@t -c user.name=t commit -q --allow-empty -m 'feat: clean work'
)
rc=0
printf '%s' '{"tool_name":"Bash","tool_input":{"command":"git push -u origin feat/clean"}}' \
  | ( cd "$sb2" && bash "$HOOK" ) >/dev/null 2>&1 || rc=$?
if [ "$rc" -eq 0 ]; then echo "PASS: clean first push allowed"; pass=$((pass+1));
else echo "FAIL: clean first push blocked (exit=$rc)"; fail=$((fail+1)); fi
rm -rf "$sb" "$sb2"

# --- F3 / D1-2: git commit -F / --file payload is scanned ---
msgdir=$(mktemp -d)
printf 'feat: y\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n' > "$msgdir/msg.txt"
run_test "block commit -F payload attribution" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -F $msgdir/msg.txt\"}}" 2
run_test "block commit --file= payload attribution" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit --file=$msgdir/msg.txt\"}}" 2
printf 'feat: y\n\nplain human message\n' > "$msgdir/clean.txt"
run_test "allow commit -F clean payload" \
  "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -F $msgdir/clean.txt\"}}" 0
rm -rf "$msgdir"

# --- F3 / D1-5: broadened agent-name list + anthropic-noreply heuristic ---
run_test "block co-authored-by Codex" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"x\n\nCo-Authored-By: Codex <codex@openai.com>\""}}' 2
run_test "block co-authored-by Cursor" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"x\n\nCo-Authored-By: Cursor <agent@cursor.com>\""}}' 2
run_test "block anthropic-noreply co-author regardless of name" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"x\n\nCo-Authored-By: Fable <noreply@anthropic.com>\""}}' 2
run_test "allow human co-author" \
  '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"x\n\nCo-Authored-By: Jane Doe <jane@example.com>\""}}' 0

t_summary
