#!/usr/bin/env bash
# GENERATED by tooling/factory/assemble.py — do NOT edit by hand.
# Mechanizes the P5 MCP/plugin invariant (spec §4.5): every materialized
# permissions.allow MCP namespace and every enabledPlugins:true key maps to a
# selected capability, and enableAllProjectMcpServers is false. Regenerate with
# `make compose`; check-compose-freshness.sh fails if this drifts.
# shellcheck disable=SC2154  # pass/fail set by ck_init (lib/check.sh)
set -uo pipefail
# shellcheck source=lib/check.sh
source "$(cd "$(dirname "$0")/lib" && pwd)/check.sh"
ck_init
ROOT="${CHECK_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
settings="$ROOT/.claude/settings.json"

ALLOWED_MCP_NS=(

)
ALLOWED_PLUGINS_TRUE=(
  "superpowers@claude-plugins-official"
)

if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$settings" 2>/dev/null; then
  echo "FAIL: settings.json is not valid JSON"; exit 1
fi

eall=$(jq -r '.enableAllProjectMcpServers' "$settings")
if [ "$eall" = "false" ]; then
  ck_pass "enableAllProjectMcpServers is false"
else
  ck_fail "enableAllProjectMcpServers must be present and false (got: $eall)"
fi

covered() { # $1 = mcp allow entry
  local e="$1" ns
  for ns in ${ALLOWED_MCP_NS[@]+"${ALLOWED_MCP_NS[@]}"}; do
    [ "$e" = "$ns" ] && return 0
    case "$e" in "$ns"__*) return 0 ;; esac
  done
  return 1
}
while IFS= read -r e; do
  [ -n "$e" ] || continue
  if covered "$e"; then ck_pass "mcp allow covered: $e"; else ck_fail "mcp allow not owned by any selected capability: $e"; fi
done < <(jq -r '.permissions.allow[] | select(startswith("mcp__"))' "$settings")

plugin_allowed() { # $1 = qualified key
  local k="$1" a
  for a in ${ALLOWED_PLUGINS_TRUE[@]+"${ALLOWED_PLUGINS_TRUE[@]}"}; do
    [ "$a" = "$k" ] && return 0
  done
  return 1
}
while IFS= read -r k; do
  [ -n "$k" ] || continue
  if plugin_allowed "$k"; then ck_pass "enabled plugin owned: $k"; else ck_fail "enabledPlugins:true not owned by any selected capability: $k"; fi
done < <(jq -r '.enabledPlugins | to_entries[] | select(.value == true) | .key' "$settings")

if [ "$fail" -eq 0 ]; then echo "Results: MCP/plugin surface OK"; else echo "Results: FAILED"; exit 1; fi
