#!/usr/bin/env bash
# gen-hooks-readme.sh — emits .claude/hooks/README.md to stdout, fully DERIVED from
# settings.json + lib/hooklib.sh + the hook sources (no hand-maintained model).
#
# Every column is computed, never typed:
#   - event/matcher : parsed from settings.json (jq -> tab-separated -> awk -F'\t')
#   - class         : grepped from the hook source (block>inject>warn, strongest wins)
#   - pinned?       : membership in HOOK_PINNED (sourced from hooklib)
#   - failure mode  : fail-closed if in HOOK_FAILCLOSED else fail-open (sourced from hooklib)
#   - disable id    : basename minus .sh
#   - test file     : tests/test-<id>.sh
#
# Determinism: LC_ALL=C, sorted rows, no timestamps — so a regenerate diffs clean
# against the committed copy. The drift gate in check-integration-hooks.sh enforces
# committed == regenerated; this is the "generated-or-gated, never a third model" rule.
set -uo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
settings="$ROOT/.claude/settings.json"
hooks_dir="$ROOT/.claude/hooks"

# shellcheck source=../.claude/hooks/lib/hooklib.sh
source "$hooks_dir/lib/hooklib.sh"

# is_member <needle> <space-separated-haystack>
is_member() {
  case " $2 " in *" $1 "*) return 0 ;; *) return 1 ;; esac
}

# event_matcher_for <hook-id> — echoes "<event>\t<matcher>" for the first settings.json
# registration of this hook id. Parses with jq (matcher coalesced to "-" so empty-matcher
# UserPromptSubmit/SessionStart hooks survive) and splits with awk -F'\t' (NEVER
# `while IFS=$'\t' read`: tab is IFS-whitespace, so bash collapses the empty matcher field).
event_matcher_for() {
  local id="$1"
  jq -r '
    .hooks | to_entries[] as $e
    | $e.value[] as $grp
    | ($grp.matcher // "-") as $m
    | $grp.hooks[]
    | select(.command != null)
    | [$e.key, $m, .command] | @tsv
  ' "$settings" 2>/dev/null \
  | awk -F'\t' -v id="$id" '
      {
        cmd = $3
        # extract the hook basename (strip path + .sh)
        if (match(cmd, /[A-Za-z0-9_-]+\.sh/)) {
          base = substr(cmd, RSTART, RLENGTH)
          sub(/\.sh$/, "", base)
          n = split(base, p, "/"); base = p[n]
          if (base == id) { print $1 "\t" $2; exit }
        }
      }
    '
}

# class_for <hook-file> — DERIVES block|inject|warn|- by grepping the source. Strongest wins.
#   block  : can exit 2 or calls audit_emit_block
#   inject : calls emit_additional_context, or cats a fabric doc to stdout (subagent-discipline)
#   warn   : calls audit_emit_warn, or echoes/printfs a WARNING/[hint]/Workflow:/NOTE advisory
class_for() {
  local f="$1"
  if grep -qE 'exit 2|audit_emit_block' "$f"; then
    echo "block"
  elif grep -qE 'emit_additional_context|cat "\$\(dirname "\$0"\)/\.\./[A-Za-z._/-]*\.md"' "$f"; then
    echo "inject"
  elif grep -q 'audit_emit_warn' "$f" \
       || grep -qiE '(echo|printf)[^=]*(warning|\[hint\]|workflow:|note:)' "$f"; then
    echo "warn"
  else
    echo "-"
  fi
}

# class_note <hook-id> — parenthetical for known multi-class hooks (the strongest-wins
# class hides a secondary behavior these hooks also have).
class_note() {
  case "$1" in
    secrets-scan)        echo " (also warns on heuristic matches)" ;;
    pre-push-secrets)    echo " (warns on heuristic matches)" ;;
    subagent-discipline) echo " (injects rubric/discipline doc to stdout)" ;;
    *)                   echo "" ;;
  esac
}

# Build the rows (one per .claude/hooks/*.sh id), then sort by event then name.
rows=""
count=0
while IFS= read -r id; do
  [ -n "$id" ] || continue
  f="$hooks_dir/$id.sh"
  em=$(event_matcher_for "$id")
  event=$(printf '%s' "$em" | awk -F'\t' '{print $1}')
  matcher=$(printf '%s' "$em" | awk -F'\t' '{print $2}')
  [ -n "$event" ] || event="(unregistered)"
  [ -n "$matcher" ] || matcher="-"
  class=$(class_for "$f")
  note=$(class_note "$id")
  if is_member "$id" "$HOOK_PINNED"; then pinned="yes"; else pinned="no"; fi
  if is_member "$id" "$HOOK_FAILCLOSED"; then failmode="fail-closed"; else failmode="fail-open"; fi
  test_file="tests/test-$id.sh"
  rows+="${event}/${matcher}	${id}	${class}${note}	${pinned}	${id}	${failmode}	${test_file}"$'\n'
  count=$((count + 1))
done < <(hook_ids)

# Self-check: row count MUST equal hook_ids | wc -l (the canonical roster).
expected=$(hook_ids | wc -l | tr -d ' ')
if [ "$count" -ne "$expected" ]; then
  echo "gen-hooks-readme: row count $count != hook_ids $expected" >&2
  exit 1
fi

# Sort rows deterministically by event/matcher then hook name (LC_ALL=C exported above).
sorted_rows=$(printf '%s' "$rows" | sort -t'	' -k1,1 -k2,2)

cat <<'HEADER'
# Hook fabric inventory

> Generated by `scripts/gen-hooks-readme.sh` — do **not** edit by hand.
> Run `bash scripts/gen-hooks-readme.sh > .claude/hooks/README.md` to refresh.
> `make integration-check` fails if this file drifts from the generator.

This workspace ships a `.claude/` hook fabric: small bash gates wired into Claude
Code lifecycle events (`PreToolUse`, `PostToolUse`, `UserPromptSubmit`,
`SessionStart`) via `.claude/settings.json`. Each hook sources
`.claude/hooks/lib/hooklib.sh` for shared mechanics (input parsing, the disable
contract, audit plumbing, secret matching). Every row below is derived from
settings.json, hooklib, and the hook source — never hand-maintained.

**Columns.**
- **class** — `block` exits non-zero to stop the tool call; `inject` adds
  advisory context (`additionalContext` or stdout) without blocking; `warn`
  prints an advisory to stdout/stderr; `-` is a pure side-effect recorder.
- **pinned?** — `yes` hooks (`HOOK_PINNED`) can never be disabled; security /
  non-negotiable enforcement.
- **disable id** — token to add to `WORKFLOW_DISABLED_HOOKS` (comma-separated) to
  turn a non-pinned hook off; `WORKFLOW_HOOKS_OFF=1` disables all non-pinned hooks.
- **failure mode** — `fail-closed` (`HOOK_FAILCLOSED`) blocks the tool call if its
  `jq` dependency is broken (better no mutation than an unscanned one); `fail-open`
  degrades to a no-op with one stderr line.
- **test file** — the hook's smoke test under `.claude/hooks/tests/`, run by
  `make hooks-test`.

HEADER

echo '| event/matcher | hook | class | pinned? | disable id | failure mode | test file |'
echo '|---|---|---|---|---|---|---|'
# The event/matcher cell can contain a literal `|` (e.g. Bash|Edit|Write…), which
# is also the markdown column delimiter — escape it so the table renders correctly.
printf '%s\n' "$sorted_rows" | awk -F'\t' '{
  gsub(/\|/, "\\|", $1)
  printf "| %s | %s | %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5, $6, $7
}'

cat <<'FOOTER'

## Boundary registrations (not hook scripts)

Two lifecycle registrations in `settings.json` are deliberately **not**
`.claude/hooks/*.sh` scripts and so are not table rows above:

- **`scripts/check-symlinks.sh`** — a `SessionStart` registration that lives under
  `scripts/` (a workspace tool, not a fabric hook). It validates the workspace
  symlink map and is appended with `|| true` so it never blocks a session.
- **`.claude/hooks/statusline.js`** — the `statusLine` command (Node, not a bash
  hook). It renders the status line and is not part of the gate fabric.

## Adopting the fabric

To vendor this hook fabric into another repo:

1. **Copy the hook directory.** Vendor `.claude/hooks/` (the `*.sh` hooks, the
   `lib/hooklib.sh` shared library, and `tests/`) into the target repo.
2. **Wire `settings.json`.** Register the hooks under the matching lifecycle
   events (`PreToolUse`/`PostToolUse`/`UserPromptSubmit`/`SessionStart`) with the
   `matcher` values shown above. Use `${CLAUDE_PROJECT_DIR:-.}` in each command so
   paths resolve regardless of cwd.
3. **Install `jq`.** Every hook inspects its JSON input with `jq`. Without it,
   `fail-open` hooks degrade to no-ops (one stderr line) and `fail-closed`
   (`HOOK_FAILCLOSED`) hooks block — so `jq` is a hard dependency for the
   security gates.
4. **Know the escape hatches.** Set them in the launching environment
   (`settings.json` `env`), not per-command:
   - `WORKFLOW_DISABLED_HOOKS=<id>,<id>` — disable specific non-pinned hooks by
     their **disable id** (the table column).
   - `WORKFLOW_HOOKS_OFF=1` — disable all non-pinned hooks at once.
   - **Pinned** hooks (`HOOK_PINNED`, the `pinned? = yes` rows) ignore both — they
     are security non-negotiables and stay on.
5. **Understand the failure contract.** `fail-open` is the default: a broken
   dependency degrades to a no-op. The `fail-closed` set (`HOOK_FAILCLOSED`)
   instead blocks the tool call, because letting an unscanned mutation through is
   worse than blocking it. The two sets are orthogonal to the pinned set.
6. **Smoke-test and inspect.** Run `make hooks-test` (shellcheck + each hook's
   `tests/test-<id>.sh`) to verify the fabric loads. Run `make wf-status` (or
   `bash .claude/hooks/lib/hooklib.sh status`) to print which hooks are
   enabled/disabled in the current environment.
FOOTER
